name: Trigger Package Generation

on:
  pull_request:
    branches: [
      "main",
    ]
    paths: [
      '.github/**',
      'SmartPlaces.Facilities/**',
    ]

env: 
  DOTNET_VERSION: '6.x' 

jobs:

  - uses: 'WillowInc/opendigitaltwins-tools/.github/workflows/SmartPlaces_Facilities.yml@main'
    with:
      build-type: 'Main Official (ASPEN)'
  
  build:
    steps:

    - name: Package
      shell: pwsh
      run: "& ./.github/workflows/scripts/buildandpack.ps1"