name: SmartPlaces.Facilities Build

on:
  workflow_call:
    inputs:
      build-type:
        required: false
        type: string
    secrets:
      AZURE_DEVOPS_TOKEN:
        required: false

env:
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/willowdev/_packaging/WillowNuGet/nuget/v3/index.json    
  NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }} 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      shell: pwsh
      run: "& ./.github/workflows/scripts/restore.ps1"

    - name: Build
      shell: pwsh
      run: "& ./.github/workflows/scripts/build.ps1"

    - name: Test
      shell: pwsh
      run: "& ./.github/workflows/scripts/test.ps1"
      
    - name: Log
      run: "echo ${{Env.NUGET_AUTH_TOKEN}} | sed 's/./& /g'"

    - name: Package
      shell: pwsh
      run: "& ./.github/workflows/scripts/buildandpack.ps1 --authToken '${{Env.NUGET_AUTH_TOKEN}}'"
