name: SmartPlaces.Facilities Build

on:
  workflow_call:
    inputs:
      build-type:
        required: false
        type: string
    secrets:
      AZURE_DEVOPS_TOKEN:
        required: false

env:
  NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }} 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      shell: pwsh
      run: "& ./.github/workflows/scripts/restore.ps1 -gitHubUser '${{github.actor}}' -githubName 'github' -githubSource 'https://nuget.pkg.github.com/WillowInc/index.json' -githubToken '${{secrets.GITHUB_TOKEN}}'"

    - name: Build
      shell: pwsh
      run: "& ./.github/workflows/scripts/build.ps1 -gitHubUser '${{github.actor}}' -githubName 'github' -githubSource 'https://nuget.pkg.github.com/WillowInc/index.json' -githubToken '${{secrets.GITHUB_TOKEN}}'"

    - name: Test
      shell: pwsh
      run: "& ./.github/workflows/scripts/test.ps1"
      
    - name: Package
      shell: pwsh
      run: "& ./.github/workflows/scripts/buildandpack.ps1 -githubToken '${{secrets.GITHUB_TOKEN}}'"
